name: "Update Spiral LUT"
on:
    schedule:
        - cron: "5 3 */8 * *"
    workflow_dispatch: {}

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.12"
            - name: Run update script
              run: python build_spiral_lut.py
            - name: Commit and push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git commit data/lut_sonames.cpp.inc -m "Update Spiral LUT" || exit 0
                  git push
